### ISSUE TITLE
Github Search App Lab Milestone

### ISSUE THREAD

**Issue by Jdoud1993** [learn-co-curriculum/phase-1-github-search-app#4]
### Canvas Link

https://learning.flatironschool.com/courses/5833/assignments/210110?module_item_id=484706

### Concern

Hello,
It looks like I have completed and submitted the Github Search App Lab. Although the lab has been graded the milestone has not been completed. I also notice that for all of the applying your learning module labs have not been check marked even though I have submitted them all.

**Comment by lizbur10** [comment]
Hi @Jdoud1993 - So sorry you ran into problems with this!

Based on your description, it sounds like this is a Canvas issue, rather than an issue with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support for Canvas or environment issues.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the  [Pair with a TC] https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Hope you are able to get this resolved!
